=head1 Configuration

Configuration is carried out in perl.  This gives all of the power of
that language, but might be a little problematic for first time
users.  

The easy way round this is to use the program
C<configure-link-controller> to do the configuration for you.  

For full system configurations, the program C<default-install> will do
much of the configuration.

=head1 Configuration Values

here is a list of variables which are used in configuration

=over4

=item $::user_address

=item $::schedule

This variable gives the location of the schedule file which is used to
determine when to check links.

=item $::links

This variable gives the location of the links-database where
information about links is held

=item $::page_index

The page index lists all of the links which are on a given page.

=item $::link_index

The link index lists all of the pages which have a given link.

=back	

=cut

=head2 per infostructure values

These only apply to normal html infostructures

=over 4 

=item $WWW::Link::Repair::infostrucbase 

the base url of the infostructure.  

=item $WWW::Link::Repair::filebase

the directory where the files for that infostructure are held.

=back
